--그룹함수
--NULL이 제외된 데이터들에 대해서 적용됨
SELECT MAX(SALARY),MIN(SALARY), SUM(SALARY),AVG(SALARY),COUNT(SALARY) FROM EMPLOYEES;
--MIN, MAX는 날짜, 문자에도 적용 됩니다.
SELECT MIN(HIRE_DATE),MAX(HIRE_DATE),MIN(FIRST_NAME),MAX(FIRST_NAME) FROM EMPLOYEES;
--COUNT() 두가지 사용방법
SELECT COUNT(*), COUNT(COMMISSION_PCT) FROM EMPLOYEES;

--부서가 80인 사람들중, 커미션이 가장 높은사람
SELECT MAX(COMMISSION_PCT) FROM EMPLOYEES WHERE DEPARTMENT_ID =80;

--그룹함수는 일반컬럼이랑 동시에 사용이 불가능
SELECT FIRST_NAME, AVG(SALARY) FROM EMPLOYEES;
--그룹함수 뒤에 OVER() 를 붙이면, 일반 컬럼과 동시에 사용이 가능함
SELECT FIRST_NAME, AVG(SALARY) OVER(),COUNT(*) OVER(),SUM(SALARY) OVER() FROM EMPLOYEES;

--GROUP BY 절 - WHERE절 ORDER절 사이에 적습니다.
SELECT DEPARTMENT_ID,SUM(SALARY),AVG(SALARY),MIN(SALARY),MAX(SALARY),COUNT(*) FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;
--GROUP화 시킨 컬럼만, SELECT구문에 적을 수 있습니다.
SELECT DEPARTMENT_ID,
       FIRST_NAME --에러
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;

--2개 이상의 그룹화(하위 그룹)
SELECT DEPARTMENT_ID,
       JOB_ID,
       SUM(SALARY)AS 부서직무별급여합,
       ROUND(AVG(SALARY))AS 부서직무별급여평균,
       COUNT(*)AS 부서인원수,
       COUNT(*) OVER() AS 부서의수 -- COUNT(*) OVER() 사용하면, 총 행의 개수를 출력가능
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID,JOB_ID ORDER BY DEPARTMENT_ID;
--그룹함수는 WHERE절에 적을 수 없음
SELECT DEPARTMENT_ID,
       AVG(SALARY)
FROM EMPLOYEES
WHERE AVG(SALARY)>=5000 --그룹의 조건을 적는 곳은 HAVING 이라고 따로 있음
GROUP BY DEPARTMENT_ID;

--HAVING절 - 그룹바이의 조건
SELECT DEPARTMENT_ID , SUM(SALARY) , COUNT (*)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING AVG(SALARY)>=10000 OR COUNT(*)>=10;

--
SELECT DEPARTMENT_ID, JOB_ID , AVG(SALARY) , COUNT(*), COUNT(COMMISSION_PCT)
FROM EMPLOYEES
WHERE JOB_ID NOT LIKE 'SA%'
GROUP BY DEPARTMENT_ID , JOB_ID
HAVING AVG(SALARY)>=10000
ORDER BY AVG(SALARY) DESC;

--부서아이디가 NULL이 아닌 데이터중에서, 입사일은 05년도인 사람들의 급여평균,급여합
--평균급여 5000이상인 데이터만, 부서아이디로 내림차순
SELECT DEPARTMENT_ID, AVG(SALARY) , SUM(SALARY) 
FROM EMPLOYEES
WHERE DEPARTMENT_ID IS NOT NULL
      AND HIRE_DATE LIKE '05%'
GROUP BY DEPARTMENT_ID
HAVING AVG(SALARY)>=5000
ORDER BY DEPARTMENT_ID DESC;

------------------------------------------------
--시험대비용
--ROLLUP - GROUP BY절과 함께 사용되고, 상위긃에 합계, 토탈 등을 구합니다.
SELECT DEPARTMENT_ID,
       SUM(SALARY),
       AVG(SALARY)
FROM EMPLOYEES
GROUP BY ROLLUP(DEPARTMENT_ID); --전체그룹에 대한 총계

SELECT DEPARTMENT_ID , JOB_ID, SUM(SALARY),AVG(SALARY)
FROM EMPLOYEES
GROUP BY ROLLUP (DEPARTMENT_ID,JOB_ID) --총계, 주그룹에 대한 총계
ORDER BY DEPARTMENT_ID;

--CUBE  - 롤업 + 서브그룹에 총계가 추가됨 
SELECT DEPARTMENT_ID,
       JOB_ID,
       SUM(SALARY),
       AVG(SALARY)
FROM EMPLOYEES
GROUP BY CUBE(DEPARTMENT_ID, JOB_ID)
ORDER BY DEPARTMENT_ID;

--GROUPING 함수 - 그룹바이로 만들어진 경우는 0반환, 롤업 또는 큐브로 만들어진 행인 경우 1을 반환
SELECT DECODE(GROUPING(DEPARTMENT_ID),1,'총계',DEPARTMENT_ID)AS DEID,
       DECODE(GROUPING(JOB_ID),1,'소계',JOB_ID)AS JID,
       AVG(SALARY),
       GROUPING(DEPARTMENT_ID),
       GROUPING(JOB_ID)
FROM EMPLOYEES
GROUP BY ROLLUP(DEPARTMENT_ID,JOB_ID)
ORDER BY DEPARTMENT_ID;

----------------------------------------------------
--1
SELECT  JOB_ID,
        COUNT(*),
        AVG(SALARY),
        MIN(HIRE_DATE)
FROM EMPLOYEES
GROUP BY JOB_ID
ORDER BY AVG(SALARY) DESC,JOB_ID;
--2
SELECT COUNT(*),
       TO_CHAR(HIRE_DATE,'YY') AS YEAR
FROM EMPLOYEES
GROUP BY TO_CHAR(HIRE_DATE,'YY')
ORDER BY YEAR ;
--3
SELECT DEPARTMENT_ID,
       AVG(SALARY)
FROM EMPLOYEES
WHERE SALARY>=1000
GROUP BY DEPARTMENT_ID
HAVING AVG(SALARY)>=2000;
--4
SELECT DEPARTMENT_ID,
       TRUNC(AVG(SALARY * (1 + COMMISSION_PCT)), 2) AS 평균,
       SUM(SALARY * (1 + COMMISSION_PCT)) AS 총합,
       COUNT(*) AS COUNT
FROM EMPLOYEES
WHERE COMMISSION_PCT IS NOT NULL
GROUP BY DEPARTMENT_ID;
--5
SELECT AVG(SALARY),
       SUM(SALARY),
       DEPARTMENT_ID
FROM EMPLOYEES
WHERE DEPARTMENT_ID IS NOT NULL AND HIRE_DATE LIKE '05%'
GROUP BY DEPARTMENT_ID
HAVING AVG(SALARY)>=10000
ORDER BY AVG(SALARY);
--6
SELECT SUM(SALARY),
       DECODE(GROUPING(JOB_ID),1,'총합',JOB_ID)
FROM EMPLOYEES
GROUP BY ROLLUP (JOB_ID)
ORDER BY JOB_ID;
--7
SELECT DECODE(GROUPING(DEPARTMENT_ID),1,'총계',DEPARTMENT_ID)AS DEID,
       DECODE(GROUPING(JOB_ID),1,'소계',JOB_ID)AS JID,
       COUNT(*),
       SUM(SALARY)
       
FROM EMPLOYEES
GROUP BY ROLLUP( DEPARTMENT_ID, JOB_ID)
ORDER BY SUM(SALARY);







